---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: frontend
spec:
  type: {{ .Values.jira.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
