# Default values for nfs-provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: quay.io/kubernetes_incubator/nfs-provisioner
  tag: latest
  pullPolicy: IfNotPresent
storage:
  hostRootPath: /srv
  mountPath: /export
storageClassName: nfs
matchExpressionKey: node-role.kubernetes.io/storage