---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
spec:
  storageClassName: {{ .Values.pvc.class_name }}
  accessModes:
  {{- range .Values.pvc.access_modes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: 1Gi
