---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  externalTrafficPolicy: Cluster
  {{- end }}
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
    - name: cluster
      port: 25672
      targetPort: cluster
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: queue-port
      port: 5672
      targetPort: 5672
    - name: cluster-port
      port: 4369
      targetPort: 4369
    - name: dist-port
      port: 25672
      targetPort: 25672
