---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP      
  selector:
    app: {{ .Chart.Name }}
