---

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "efs-provisioner.serviceAccountName" . }}
  labels:
    app: {{ template "efs-provisioner.name" . }}
{{- end }}
