---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: kube-system
  labels:
    k8s-app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  selector:
    k8s-app: {{ .Chart.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: api
      port: 8080
      targetPort: api
      protocol: TCP
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
