---

#
#
#

name: traefik-aws
apiVersion: v1
description: Træfik is a modern HTTP reverse proxy and load balancer
home: https://traefik.io/
icon: https://docs.traefik.io/img/traefik.logo.png
keywords:
  - traefik
  - ingress
maintainers:
  - name: Maintainer
    email: support@example.com
    url: https://www.example.com
sources:
  - https://github.com/containous/traefik
  - https://gitlab.example.com/devops/helm-charts/traefik