---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: frontend
spec:
  type: {{ .Values.confluence.service.type }}
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
    - name: synchrony
      port: 8091
      targetPort: synchrony
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
