---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: devops
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: devel
          image: "{{ .Values.registry_address }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          args:
            - "tail"
            - "-f"
            - "/dev/null"
          resources:
            limits:
              cpu: "300m"
              memory: "500Mi"
            requests:
              cpu: "10m"
              memory: "100Mi"
