---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}
    namespace: kube-system
roleRef:
  kind: Role
  name: {{ .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
