---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeswitch-{{ .Values.environment }}
spec:
  storageClassName: {{ .Values.pvc.class_name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
