---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
