---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voip-developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: voip
